# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_sobytia', '0003_auto_20171221_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Konkurs',
            new_name='SmotrKonkurs',
        ),
        migrations.RenameModel(
            old_name='KonkursImage',
            new_name='SmotrKonkursImage',
        ),
        migrations.AlterModelOptions(
            name='smotrkonkurs',
            options={'verbose_name': 'смотр-конкурс', 'verbose_name_plural': 'смотры-конкурсы'},
        ),
        migrations.AlterModelOptions(
            name='smotrkonkursimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
